# H2 Database Configuration
# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:legalmatch_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

