# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/legalmatch_db
spring.datasource.username=postgres
spring.datasource.password=0105cs243d21

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 console
spring.h2.console.enabled=false